alpha1/Models/Dish.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using alpha.Repositories;

namespace alpha.Models
{
    public class Dish:IIdentity
    {
        public Dish()
        {
        }

        public Guid Id
        {
            get;
            set;
        }

        [Required]
        public string Name
        {
            get;
            set;
        }

        public IList<Item> Items
        {
            get;
            set;
        }


    }
}

alpha1/Models/ErrorViewModel.cs
using System;

namespace alpha1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

alpha1/Models/Inventory.cs
using System;
using System.Collections.Generic;

namespace alpha.Models
{
    public class Inventory
    {
        public Inventory()
        {
        }

        public IList<Item> Items
        {
            get;
            set;
        }
    }
}

alpha1/Models/Item.cs
using System;
using alpha.Repositories;

namespace alpha.Models
{
    public class Item: IIdentity
    {
        public Item()
        {
        }
        public Guid Id
        {
            get;
            set;
        }

        public Guid DishId
        {
            get;
            set;
        }

        public string Name
        {
            get;
            set;
        }

        public int Quantity
        {
            get;
            set;
        }

        public ItemType Type
        {
            get;
            set;
        }

    }
}

alpha1/Models/ItemType.cs
namespace alpha.Models
{
    public enum ItemType
    {
        Meat,
        Fruit,
        Vegetable,
        Drink,
        Snack,
        Other
    }
}

alpha1/Models/Menu.cs
using System;
using System.Collections.Generic;

namespace alpha.Models
{
    public class Menu
    {
        public Menu()
        {
        }

        public string Name
        {
            get;
            set;
        }

        public IList<Dish> Dishes
        {
            get;
            set;
        }
    }
}

alpha1/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;

namespace alpha.Models
{
    public class ShoppingCart
    {
        public ShoppingCart()
        {
        }

        public IList<Item> ItemChecklist
        {
            get;
            set;
        }

        public IList<Item> BoughtItems
        {
            get;
            set;
        }
    }
}

alpha1/Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using alpha.Models;
using alpha.Services;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace alpha.Controllers
{
    [Route("[controller]/[action]")]
    public class DishController : Controller
    {

        private readonly IMealService mealService;

        public DishController(IMealService mealService)
        {
            this.mealService = mealService;
        }

        [HttpGet]
        public IActionResult Index(Guid ?id)
        {
            if(id.HasValue && id != Guid.Empty){
                var dish = mealService.GetDish(id.Value);
                return View("Index", dish);
            }
            return View("Index", new Dish() {Items = new List<Item>() {new Item()}});
        }

        [HttpPost()]
        public IActionResult Save([FromForm]Dish dish)
        {
            if(ModelState.IsValid){
                if (dish.Id != Guid.Empty)
                {
                    mealService.UpdateDish(dish);
                }
                else
                {
                    dish = mealService.AddDish(dish);
                }

                return RedirectToAction("Index", "Dish", new { id = dish.Id });
            }
            return View(ModelState);
        }


        [HttpPost()]
        public IActionResult Delete([FromForm]Guid id)
        {
            mealService.DeleteDish(id);
            return Ok();
        }
    }
}

alpha1/Controllers/HomeController.cs
using System;
using alpha.Services;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace alpha.Controllers
{
    [Route("[controller]/[action]")]
    [Produces("application/json")]
    public class HomeController : Controller
    {

        private readonly IMealService mealService;

        public HomeController(IMealService mealService)
        {
            this.mealService = mealService;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var dishes = mealService.GetDishes();
            return View(dishes);
        }

        [HttpGet]
        public IActionResult DeleteDish(Guid id){
            mealService.DeleteDish(id);
            return RedirectToAction("Index");
        }



    }
}

alpha1/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using alpha.Models;
using alpha.Services;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace alpha.Controllers
{
    public class ItemController : Controller
    {
        private readonly IMealService mealService;
        public ItemController(IMealService mealService)
        {
            this.mealService = mealService;
        }
        // GET: /<controller>/
        public IActionResult Index(Guid dishId, Guid ?itemId)
        {
            var item = new Item() { DishId = dishId, Id = itemId ?? Guid.Empty };

            if(itemId.HasValue){
                item = mealService.GetItem(itemId.Value);
            }


            return View("Index", item);
        }

        [HttpPost()]
        public IActionResult SaveItem([FromForm] Item item)
        {
            if(item.Id != Guid.Empty){
                mealService.UpdateItem(item);
            }
            else{
                var itemId = mealService.AddItemToDish(item);
            }

            return RedirectToAction("Index", "Dish", new {id = item.DishId});
        }

        [HttpGet]
        public IActionResult DeleteItem(Guid itemId){
            var item = mealService.GetItem(itemId);
            mealService.DeleteItem(itemId);
            return RedirectToAction("Index","Dish", new { id = item.DishId });
        }
    }
}

alpha1/Views/Dish/Index.cshtml
@model alpha.Models.Dish
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

<form asp-controller="Dish" asp-action="Save" method="post" id="frmSaveDish">
    <label asp-for="Name"></label>  <input asp-for="Name" data-val="true" data-val-required="The name field is required."/><span asp-validation-for="Name"></span> <br />
    <input type="hidden" id="id" name="id" value="@Model.Id" />
    <input type="submit" id="btnSaveDish"/>
</form>
Item list:
@if (Model.Items != null && Model.Items.Any())
{
    <ul>

        @foreach (var i in Model.Items)
        {
        <li>@i.Name: @i.Quantity <a asp-controller="Item" asp-action="Index" asp-route-dishId="@Model.Id" asp-route-itemId="@i.Id">Edit</a> <a asp-controller="Item" asp-action="DeleteItem" asp-route-itemId="@i.Id">Delete</a></li>
        }


    </ul>
}
    <a asp-controller="Item" asp-action="Index" asp-route-dishId="@Model.Id" id="lnkAddItem">Add Item</a>

    <a asp-controller="Home" id="lnkBackHome">back to home</a>






alpha1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

alpha1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

alpha1/Views/Home/Index.cshtml

@model IEnumerable<alpha.Models.Dish>


<h1>Dishes</h1>
<ul>
    @foreach (var d in Model)
    {
        <li>@d.Name <a asp-controller="dish" asp-route-id="@d.Id">Edit</a><a asp-controller="home" asp-action="DeleteDish" asp-route-id="@d.Id">Remove</a>
        <div>
            @if (d.Items != null && d.Items.Any())
            {
            <ul>
                @foreach (var i in d.Items)
                {
                    <li>@i.Name @i.Type</li>

                }
            </ul>
            }
        </div>
        </li>




    }
</ul>
<a asp-controller="Dish" asp-action="Index" id="lnkAddDish">Add Dish</a>

alpha1/Views/Index.cshtml

@model IEnumerable<alpha.Models.Dish>


<h1>Dishes</h1>
<ul>
    @foreach (var d in Model)
    {
        <li>@d.Name <a asp-controller="dish" asp-route-id="@d.Id">Edit</a><a asp-controller="home" asp-action="DeleteDish" asp-route-id="@d.Id">Remove</a>
        <div>
            @if (d.Items != null && d.Items.Any())
            {
            <ul>
                @foreach (var i in d.Items)
                {
                    <li>@i.Name @i.Type</li>

                }
            </ul>
            }
        </div>
        </li>




    }
</ul>
<a asp-controller="Dish" asp-action="Index" id="lnkAddDish">Add Dish</a>

alpha1/Views/Item/Index.cshtml
@model alpha.Models.Item
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<form asp-controller="Item" asp-action="SaveItem" method="post" id="frmItem">

    <b>Name</b> <input asp-for="@Model.Name" />
    <b>Quantity</b> <input asp-for="@Model.Quantity" />
    <b>Type</b> <input asp-for="@Model.Type" />
    <input asp-for="@Model.Id" type="hidden" />
    <input asp-for="@Model.DishId" type="hidden"/>
    <input type="submit" id="btnAddItem"/>
</form>

alpha1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - alpha1</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">alpha1</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - alpha1</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
</html>